// Include the bindings generated by build.rs.
// Not modifying the src directory makes this crate easier to publish.
#[allow(dead_code)]
pub mod blit {
    include!(concat!(env!("OUT_DIR"), "/blit.rs"));
}
#[allow(dead_code)]
pub mod deferred {
    include!(concat!(env!("OUT_DIR"), "/deferred.rs"));
}
#[allow(dead_code)]
pub mod model {
    include!(concat!(env!("OUT_DIR"), "/model.rs"));
}
#[allow(dead_code)]
pub mod morph {
    include!(concat!(env!("OUT_DIR"), "/morph.rs"));
}
#[allow(dead_code)]
pub mod snn_filter {
    include!(concat!(env!("OUT_DIR"), "/snn_filter.rs"));
}
#[allow(dead_code)]
pub mod solid {
    include!(concat!(env!("OUT_DIR"), "/solid.rs"));
}
#[allow(dead_code)]
pub mod unbranch_to_depth {
    include!(concat!(env!("OUT_DIR"), "/unbranch_to_depth.rs"));
}
