use clap::Parser;
use xc3_model::{gltf::GltfFile, load_model, GBufferDatabase};

/// Convert wimdo and wismhd models to glTF for
/// Xenoblade 1 DE, Xenoblade 2, and Xenoblade 3.
#[derive(Parser)]
#[command(author, version, about, long_about = None)]
#[command(propagate_version = true)]
struct Cli {
    /// The input `.wimdo` or `.wismhd` file.
    input: String,
    /// The output `.gltf` file.
    /// Images will be saved to the same directory as the output.
    output: String,
    /// The GBuffer JSON database generated by xc3_shader.
    database: Option<String>,
}

fn main() {
    let cli = Cli::parse();
    let start = std::time::Instant::now();

    let database = cli.database.map(GBufferDatabase::from_file);

    let roots = if cli.input.ends_with(".wismhd") {
        xc3_model::load_map(&cli.input, database.as_ref())
    } else {
        let root = load_model(&cli.input, database.as_ref());

        vec![root]
    };

    let name = std::path::Path::new(&cli.output)
        .with_extension("")
        .file_name()
        .unwrap()
        .to_string_lossy()
        .to_string();

    let file = GltfFile::new(&name, &roots);
    file.save(&cli.output);

    println!("Converted {} roots in {:?}", roots.len(), start.elapsed());
}
