[package]
name = "xc3_gltf"
version = "0.14.0"
edition = "2021"

[dependencies]
xc3_model = { path = "../xc3_model", features = ["gltf"] }
clap = { version = "4.2.7", features = ["derive"] }
anyhow = "1.0"
log = "0.4.19"
simple_logger = "4.2.0"
