[package]
name = "xc3_gltf"
version = "0.20.0"
edition = "2021"

[dependencies]
xc3_model = { path = "../xc3_model", features = ["gltf"] }
clap = { workspace = true, features = ["derive"] }
anyhow.workspace = true
log.workspace = true
simple_logger.workspace = true
